"""Initial migration

Revision ID: 7bf730be217f
Revises: 
Create Date: 2025-09-02 21:01:27.075085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf730be217f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('hymns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hymn_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hymns_hymn_number'), 'hymns', ['hymn_number'], unique=True)
    op.create_index(op.f('ix_hymns_id'), 'hymns', ['id'], unique=False)
    op.create_table('hymn_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hymn_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('stanza_number', sa.Integer(), nullable=True),
    sa.Column('content_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hymn_id'], ['hymns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hymn_content_id'), 'hymn_content', ['id'], unique=False)
    op.create_table('content_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hymn_content_id', sa.Integer(), nullable=False),
    sa.Column('line_text', sa.Text(), nullable=False),
    sa.Column('line_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hymn_content_id'], ['hymn_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_lines_id'), 'content_lines', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_lines_id'), table_name='content_lines')
    op.drop_table('content_lines')
    op.drop_index(op.f('ix_hymn_content_id'), table_name='hymn_content')
    op.drop_table('hymn_content')
    op.drop_index(op.f('ix_hymns_id'), table_name='hymns')
    op.drop_index(op.f('ix_hymns_hymn_number'), table_name='hymns')
    op.drop_table('hymns')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
